import fs from 'node:fs/promises';
import path from 'node:path';
import { createHash } from 'node:crypto';
import { fileURLToPath } from 'node:url';
import { validateSchema, validURL } from './schema.mjs';

export const ROOT = path.resolve(path.dirname(fileURLToPath(import.meta.url)), '..');
export const START = '<!-- CATALOG:START -->';
export const END = '<!-- CATALOG:END -->';
const generated = '<!-- Generated by npm run build. Edit data/cases/*.json. -->\n\n';
const labels = {
  full: '完整文本', partial: '局部 Prompt', excerpt: '原文节选', link_only: '完整 Prompt 见来源',
  not_found: '未找到 Prompt', not_public: '作者未公开 Prompt',
  primary: '已读取作者原帖', primary_republication: '已读取作者再发布页面', secondary: '仅核对整理来源', none: '尚未核验',
  unchecked: '未实测播放', verified: '已人工播放核对', error: '读取时媒体加载失败',
  accessible: '已读取', inaccessible: '本次无法读取', unknown: '未检查',
  video_generation: '视频生成', image_generation: '图像生成', audio_generation: '声音生成',
  editing: '剪辑', script_assistance: '剧本辅助', first_frame: '首帧', last_frame: '尾帧',
  image: '图片', video: '视频', audio: '音频', linked: '已提供来源链接', missing: '素材缺失'
};
export const label = value => labels[value] ?? value;
export const json = value => JSON.stringify(value, null, 2) + '\n';
const cmp = (a, b) => a < b ? -1 : a > b ? 1 : 0;
export const md = s => String(s).replace(/&/g, '&amp;').replace(/</g, '&lt;').replace(/>/g, '&gt;').replace(/[\\`*_{}\[\]()#!|~]/g, '\\$&').replace(/\r?\n/g, ' ');
const link = (title, url) => `[${md(title)}](<${url}>)`;
const html = value => String(value).replace(/[&<>"']/g, ch => ({ '&': '&amp;', '<': '&lt;', '>': '&gt;', '"': '&quot;', "'": '&#39;' }[ch]));
const fenced = text => {
  const fence = '`'.repeat(Math.max(3, ...[...text.matchAll(/`+/g)].map(m => m[0].length + 1)));
  return `${fence}text\n${text}\n${fence}`;
};
export const isVideoAttachment = url => /^https:\/\/github\.com\/user-attachments\/assets\/[a-f0-9]{8}(?:-[a-f0-9]{4}){3}-[a-f0-9]{12}$/.test(url);
export function videoBlock(c) {
  const display = c.video.display;
  if (display?.embed_url && isVideoAttachment(display.embed_url)) return display.embed_url;
  if (display?.poster_url) return `<a href="${html(c.video.page_url)}"><img src="${html(display.poster_url)}" alt="${html(c.title)} — 点击观看原视频" width="720"></a>\n\n${link('▶ 点击封面观看原视频', c.video.page_url)}`;
  return `${link('▶ 观看原视频', c.video.page_url)} · 暂无可嵌入视频或封面。`;
}
export function keyFor(name) {
  const prefix = name.toLowerCase().replace(/[^a-z0-9]+/g, '-').replace(/^-|-$/g, '').slice(0, 48) || 'group';
  return `${prefix}-${createHash('sha256').update(name).digest('hex').slice(0, 8)}`;
}

export function canonicalURL(value) {
  if (!validURL(value)) throw new Error(`Invalid source URL: ${value}`);
  const u = new URL(value);
  const host = u.hostname.toLowerCase().replace(/^(www|m|mobile|old)\./, '');
  if (['x.com', 'twitter.com'].includes(host)) {
    const match = u.pathname.match(/\/status\/(\d+)/);
    if (match) return `https://x.com/i/status/${match[1]}`;
  }
  if (host === 'reddit.com') {
    const match = u.pathname.match(/\/comments\/([a-z0-9]+)/i);
    if (match) return `https://reddit.com/comments/${match[1].toLowerCase()}`;
  }
  if (host === 'redd.it') return `https://reddit.com/comments/${u.pathname.split('/')[1].toLowerCase()}`;
  if (['youtube.com', 'youtu.be'].includes(host)) {
    const id = host === 'youtu.be' ? u.pathname.split('/')[1] : u.searchParams.get('v') ?? u.pathname.match(/^\/(?:shorts|embed)\/([^/]+)/)?.[1];
    if (id) return `https://youtube.com/watch?v=${encodeURIComponent(id)}`;
  }
  u.hostname = host;
  u.hash = '';
  for (const key of [...u.searchParams.keys()]) if (/^utm_/i.test(key) || ['fbclid', 'gclid', 'si'].includes(key)) u.searchParams.delete(key);
  u.searchParams.sort();
  u.pathname = u.pathname.replace(/\/$/, '') || '/';
  return u.toString();
}
export const identity = c => `${canonicalURL(c.source.url)}#${c.source.item_key}`;
export const published = cases => cases.filter(c => c.review.status === 'approved').sort((a, b) => cmp(a.id, b.id));
export const hasPrompt = c => !['not_found', 'not_public'].includes(c.prompt.status);

export function validateCases(cases, schema, today = new Date().toISOString().slice(0, 10)) {
  const errors = [];
  const ids = new Set(), sources = new Map();
  for (const c of cases) {
    const structural = validateSchema(c, schema, c?.id ?? '$');
    errors.push(...structural);
    if (structural.length) continue;
    const fail = message => errors.push(`${c.id}: ${message}`);
    if (ids.has(c.id)) fail('duplicate id');
    ids.add(c.id);
    const sourceKey = identity(c);
    if (sources.has(sourceKey)) fail(`duplicate work/source item with ${sources.get(sourceKey)}`);
    sources.set(sourceKey, c.id);
    for (const date of [c.source.published_at, c.collected_at, c.verification.checked_at, c.review.reviewed_at, c.video.checked_at]) {
      if (date && date > today) fail('date is in the future');
    }
    const textRequired = ['full', 'partial', 'excerpt'].includes(c.prompt.status);
    if (textRequired && !c.prompt.original?.trim()) fail('prompt status requires original text');
    if (!textRequired && c.prompt.original !== null) fail('this prompt status requires original=null');
    if (hasPrompt(c) && !c.prompt.source_url) fail('prompt needs its own evidence URL');
    if (!hasPrompt(c) && (c.prompt.translation_zh !== null || c.prompt.language !== null)) fail('missing prompt cannot have a translation/language');
    if (c.prompt.translation_zh && !c.prompt.original) fail('translation requires original text');
    if (c.review.status === 'approved') {
      if (!c.review.reviewed_at || !c.author.name || !c.author.url) fail('approved case requires dated review and author');
      if (!['primary', 'primary_republication'].includes(c.verification.level)) fail('approved case requires primary evidence');
      if (!c.verification.checked_at || !c.verification.evidence_urls.length) fail('approved case requires dated evidence');
      if (!c.verification.ai_evidence.trim()) fail('approved case needs evidence that this work used AI video');
      if (c.verification.level === 'primary' && c.source.access !== 'accessible') fail('primary verification requires an accessible original');
      if (!c.summary_zh.trim()) fail('approved case needs a summary');
    }
    if (c.video.playback === 'verified' && (!c.video.checked_at || !c.video.notes.trim())) fail('playback verification requires a date and viewing notes');
    if (c.video.display) {
      const d = c.video.display;
      if (!d.embed_url && !d.poster_url) fail('video display requires an embed or poster');
      if (d.embed_url && !isVideoAttachment(d.embed_url)) fail('embed_url must be a stable GitHub video attachment URL');
      if (d.checked_at > today) fail('video display date is in the future');
    }
    if (c.reproduction.status === 'reproduced' && (!c.reproduction.evidence_url || !c.reproduction.notes.trim())) fail('reproduction needs output evidence and notes');
    if (c.rights.status === 'permission_granted' && !c.rights.evidence_url) fail('permission requires evidence');
    for (const m of c.models) if (c.review.status === 'approved' && !m.evidence_url) fail('each disclosed model needs evidence');
  }
  return errors;
}

export async function loadCases(root = ROOT) {
  const schema = JSON.parse(await fs.readFile(path.join(root, 'schema/case.schema.json'), 'utf8'));
  const cases = [], locations = new Map();
  for (const dir of ['data/cases', 'data/candidates']) {
    const names = (await fs.readdir(path.join(root, dir))).filter(n => n.endsWith('.json')).sort();
    for (const name of names) {
      const c = JSON.parse(await fs.readFile(path.join(root, dir, name), 'utf8'));
      if (name !== `${c.id}.json`) throw new Error(`${dir}/${name}: filename must match id`);
      if (dir === 'data/candidates' && c.review?.status === 'approved') throw new Error(`${name}: move approved case to data/cases`);
      cases.push(c); locations.set(c.id, dir);
    }
  }
  const errors = validateCases(cases, schema);
  if (errors.length) throw new Error(errors.join('\n'));
  return { cases, schema, locations };
}

const modelNames = c => c.models.filter(m => m.role === 'video_generation').map(m => m.name);
function modelText(c) {
  return [...new Set(modelNames(c))].map(md).join(' · ') || '模型未公开';
}
function table(cases, prefix) {
  return '| 案例 | 视频模型 | 平台 | Prompt |\n|---|---|---|---|\n' + cases.map(c =>
    `| ${link(c.title, `${prefix}${c.id}.md`)} | ${modelText(c)} | ${md(c.platform)} | ${label(c.prompt.status)} |`).join('\n');
}
function groups(cases, dimension) {
  const out = new Map();
  for (const c of cases) {
    const names = dimension === 'model' ? modelNames(c) : [c[dimension]];
    for (const name of new Set(names.length ? names : ['模型未公开'])) {
      if (!out.has(name)) out.set(name, []);
      out.get(name).push(c);
    }
  }
  return [...out.entries()].sort(([a], [b]) => cmp(a, b));
}
function modelVersion(c) {
  return c.models.filter(m => m.role === 'video_generation').map(m => md(m.name + (m.version ? ` ${m.version}` : ''))).join(' · ') || '模型未公开';
}
function fold(title, body) {
  return `<details>\n<summary>${html(title)}</summary>\n\n${body}\n\n</details>`;
}
function gallery(cases, prefix) {
  const cards = cases.map(c => `\n\n### ${link(c.title, `${prefix}${c.id}.md`)}\n\n${videoBlock(c)}\n\n**${modelVersion(c)}** · ${md(c.platform)} · ${label(c.prompt.status)}\n\n${md(c.summary_zh)}\n\n${link(hasPrompt(c) ? '查看 Prompt →' : '查看制作说明 →', `${prefix}${c.id}.md`)}\n\n`);
  const rows = [];
  for (let i = 0; i < cards.length; i += 2) rows.push(`<tr>\n<td width="50%" valign="top">${cards[i]}</td>\n<td width="50%" valign="top">${cards[i + 1] ?? '\n\n'}</td>\n</tr>`);
  return `<table>\n${rows.join('\n')}\n</table>`;
}
export function detail(c) {
  const lines = [generated + link('← 返回视频画廊', '../../README.md'), `# ${md(c.title)}`, videoBlock(c),
    `**模型：** ${modelVersion(c)} · **来源：** ${link(c.author.name, c.source.url)} · ${md(c.platform)}`,
    md(c.summary_zh), '## Prompt', `**${label(c.prompt.status)}** · ${md(c.prompt.scope)}`];
  if (c.prompt.original) {
    const quote = fenced(c.prompt.original);
    lines.push(c.platform === 'Reddit' ? quote.split('\n').map(line => `> ${line}`).join('\n') : quote);
  }
  else lines.push(c.prompt.status === 'link_only' ? link('前往作者页面查看完整 Prompt', c.prompt.source_url) : '暂未收录作者的原始 Prompt。');
  if (c.prompt.source_url) lines.push(link('查看 Prompt 原文 ↗', c.prompt.source_url));
  if (c.prompt.translation_zh) lines.push(fold('中文译文（整理者翻译）', fenced(c.prompt.translation_zh)));
  if (c.prompt.recreated) lines.push(fold('整理者另拟 Prompt（非作者原文）', fenced(c.prompt.recreated)));
  const extra = [
    '**使用说明**', md(c.prompt.notes),
    '**模型与工具**', c.models.map(m => `- ${md(m.name)} ${md(m.version ?? '（版本未公开）')} · ${md(label(m.role))}`).join('\n'),
    '**参考素材**', c.references.length ? c.references.map(r => `- ${md(label(r.kind))}：${r.url ? link('素材来源', r.url) : '未取得素材链接'}。${md(r.notes)}`).join('\n') : '未披露额外参考素材。',
    '**制作过程**', c.workflow_notes.map(s => `- ${md(s)}`).join('\n') || '未披露。',
    '**来源记录**', `${label(c.verification.level)} · ${c.verification.checked_at}。${md(c.verification.ai_evidence)}`,
    c.verification.evidence_urls.map(u => `- ${link('核验来源', u)}`).join('\n'),
    `Prompt 定位：${md(c.prompt.locator)}`, c.verification.notes.map(s => `- ${md(s)}`).join('\n'),
    `播放记录：${label(c.video.playback)}。${md(c.video.notes)}`,
    c.video.display ? `展示素材：${link('对应关系依据', c.video.display.evidence_url)} · ${c.video.display.checked_at}。${md(c.video.display.notes)}` : '',
    md(c.rights.notes), md(c.reproduction.notes)
  ];
  lines.push(fold('制作过程、参考素材与来源记录', extra.filter(Boolean).join('\n\n')),
    `${link('原始记录', `../../data/cases/${c.id}.json`)} · ${link('署名与移除', '../../RIGHTS.md')}`);
  return lines.filter(Boolean).join('\n\n') + '\n';
}

export function generateOutputs(cases, readme) {
  if (readme.split(START).length !== 2 || readme.split(END).length !== 2 || readme.indexOf(END) < readme.indexOf(START)) throw new Error('README must have exactly one ordered catalog marker pair');
  const live = published(cases), prompts = live.filter(hasPrompt), inspirations = live.filter(c => !hasPrompt(c));
  const inline = live.filter(c => c.video.display?.embed_url).length;
  const content = [
    `<p align="center"><strong>${live.length} 个案例 · ${prompts.length} 份 Prompt 资料 · ${groups(live, 'model').length} 类视频模型</strong></p>`,
    '<a name="browse"></a>\n\n## 🧭 按主题浏览'
  ];
  const out = new Map();
  for (const [dimension, title] of [['model', '视频模型'], ['category', '创作主题'], ['platform', '来源平台']]) {
    const index = groups(live, dimension);
    content.push(`**${title}**：` + index.map(([name, entries]) => link(`${name} · ${entries.length}`, `docs/by-${dimension}/${keyFor(name)}.md`)).join(' / '));
    for (const [name, entries] of index) out.set(`docs/by-${dimension}/${keyFor(name)}.md`, generated + `# ${md(name)}\n\n${link('← 返回视频画廊', '../../README.md')}\n\n${table(entries, '../cases/')}\n`);
  }
  const order = entries => [...entries].sort((a, b) => Number(!!b.video.display?.embed_url) - Number(!!a.video.display?.embed_url) || cmp(a.id, b.id));
  content.push('<a name="gallery"></a>\n\n## 🎬 视频与 Prompt',
    `先看作品，再打开详情复制 Prompt。${inline} 个案例使用页内播放器；其余案例点击视频封面前往原帖播放。`,
    prompts.length ? gallery(order(prompts), 'docs/cases/') : '暂无。',
    '<a name="inspiration"></a>\n\n## 💡 灵感与制作过程',
    '这些作品已披露使用的 AI 视频工具，暂未收录原始 Prompt。',
    inspirations.length ? gallery(order(inspirations), 'docs/cases/') : '暂无。');
  const body = readme.slice(0, readme.indexOf(START) + START.length) + '\n\n' + content.join('\n\n') + '\n\n' + readme.slice(readme.indexOf(END));
  out.set('README.md', body);
  for (const c of live) out.set(`docs/cases/${c.id}.md`, detail(c));
  out.set('data/catalog.json', json({ schema_version: 1, cases: live }));
  return out;
}

const removable = name => /^docs\/(?:cases|by-model|by-category|by-platform)\/[a-z0-9-]+\.md$/.test(name);
export async function build(root = ROOT, check = false) {
  const { cases } = await loadCases(root);
  const outputs = generateOutputs(cases, await fs.readFile(path.join(root, 'README.md'), 'utf8'));
  const manifestName = '.generated-files.json';
  let previous = [];
  try { previous = JSON.parse(await fs.readFile(path.join(root, manifestName), 'utf8')); }
  catch (e) { if (e.code !== 'ENOENT') throw e; }
  if (!Array.isArray(previous) || previous.some(n => typeof n !== 'string' || !(removable(n) || ['README.md', 'data/catalog.json'].includes(n)))) throw new Error('Invalid generated manifest');
  const obsolete = previous.filter(n => !outputs.has(n));
  const expected = [...outputs.keys()].sort();
  outputs.set(manifestName, json(expected));
  const problems = [];
  for (const [name, contents] of outputs) {
    const filename = path.join(root, name);
    if (check) {
      try { if (await fs.readFile(filename, 'utf8') !== contents) problems.push(`${name}: stale generated output`); }
      catch (e) { if (e.code !== 'ENOENT') throw e; problems.push(`${name}: missing generated output`); }
    } else {
      await fs.mkdir(path.dirname(filename), { recursive: true });
      await fs.writeFile(filename, contents);
    }
  }
  for (const name of obsolete) {
    if (!removable(name)) throw new Error(`Refusing to remove ${name}`);
    if (check) problems.push(`${name}: obsolete generated output`);
    else await fs.rm(path.join(root, name), { force: true });
  }
  if (problems.length) throw new Error(problems.join('\n'));
  return { cases: published(cases).length, outputs: outputs.size };
}

export function draft({ id, url, platform = 'Unknown', title = '待核验的视频线索', author_name = null, author_url = null, item_key = 'main' }, date = new Date().toISOString().slice(0, 10)) {
  if (!validURL(url)) throw new Error('url must be an HTTP(S) URL without credentials');
  id ??= `candidate-${createHash('sha256').update(canonicalURL(url) + '#' + item_key).digest('hex').slice(0, 12)}`;
  return {
    id, title, summary_zh: '', platform,
    source: { url, item_key, locator: '待核验', published_at: null, access: 'unknown' },
    author: { name: author_name, url: author_url }, collected_at: date,
    models: [], category: '待分类', tags: [],
    prompt: { status: 'not_found', original: null, language: null, translation_zh: null, recreated: null, source_url: null, scope: '待核验', locator: '', notes: '仅导入线索，尚未提取或核实 Prompt。' },
    references: [], workflow_notes: [],
    video: { page_url: url, alternate_urls: [], playback: 'unchecked', checked_at: null, notes: '未实测播放。' },
    verification: { level: 'none', checked_at: null, evidence_urls: [], ai_evidence: '', notes: ['待确认原作者、AI 视频依据及对应 Prompt。'] },
    review: { status: 'pending', reviewed_at: null },
    rights: { status: 'link_only', evidence_url: null, notes: '仅保存公开页面链接，不下载或托管媒体。' },
    reproduction: { status: 'not_attempted', evidence_url: null, notes: '未进行实际生成。' }
  };
}

export async function importRows(rows, root = ROOT) {
  const { cases, schema } = await loadCases(root);
  const ids = new Set(cases.map(c => c.id)), seen = new Set(cases.map(identity));
  const additions = [], skipped = [];
  // Validate the whole batch before writing anything. Never trust incoming review/model/prompt fields.
  const allowed = new Set(['id', 'url', 'platform', 'title', 'author_name', 'author_url', 'item_key']);
  for (const [index, row] of rows.entries()) {
    if (!row || typeof row !== 'object' || Array.isArray(row)) throw new Error(`Row ${index + 1}: expected object`);
    if (Object.keys(row).some(k => !allowed.has(k))) throw new Error(`Row ${index + 1}: unsupported import field`);
    const c = draft(row), errors = validateCases([c], schema);
    if (errors.length) throw new Error(errors.join('\n'));
    if (seen.has(identity(c))) { skipped.push(c.source.url); continue; }
    if (ids.has(c.id)) throw new Error(`ID collision: ${c.id}`);
    seen.add(identity(c)); ids.add(c.id); additions.push(c);
  }
  for (const c of additions) await fs.writeFile(path.join(root, 'data/candidates', `${c.id}.json`), json(c), { flag: 'wx' });
  return { added: additions.length, skipped: skipped.length };
}
